---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster-01
  region: us-east-2
  version: "1.27"

kubernetesNetworkConfig:
  ipFamily: IPv4
addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    version: latest

iam:
  withOIDC: true

managedNodeGroups:
  - name: nodegroup1
    instanceType: t2.large
    minSize: 2
    desiredCapacity: 3
    maxSize: 4
    availabilityZones: ["us-east-2a", "us-east-2b", "us-east-2c"]
    volumeSize: 50
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub